In [1]:
import numpy as np

In [3]:
# Array 1d
d1 = np.array([1, 2, 3])
print(d1)

[1 2 3]


In [4]:
d1.shape

(3,)

In [6]:
d1.ndim #número de dimensões

1

In [7]:
d1.dtype

dtype('int64')

In [9]:
d2 = np.array([[1, 2, 3], [4, 5, 6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [10]:
d2.shape

(2, 3)

In [11]:
d2.ndim

2

In [14]:
d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d3)

d3.shape


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [15]:
d3.ndim

3