In [2]:
import numpy as np

In [4]:
a = np.array([[2, 3, 4, 5], [6, 7, 8, 9]])
print(a)

[[2 3 4 5]
 [6 7 8 9]]


In [10]:
# array[row, col]
a[1, 2]

8

In [12]:
print(a[0, :])

[2 3 4 5]


In [14]:
a[:, 1]

array([3, 7])